export enum PermissionEnum {
    BANVE = 'BANVE',
    HOANVE = 'HOANVE',
    YEUCAUHOANVE = 'YEUCAUHOANVE',
    SOATVE = 'SOATVE',
    BAOCAODOANHTHU = 'BAOCAODOANHTHU',
    QLPHIM = 'QLPHIM',
    QLLICHCHIEU = 'QLLICHCHIEU',
    QLPHONGCHIEU = 'QLPHONGCHIEU',
    QLSUATCHIEU = 'QLSUATCHIEU',
    QLGHE = 'QLGHE',
    MUAVE = 'MUAVE',
}

export default PermissionEnum;
