export enum PermissionEnum {
  BANVE = 'BANVE',
  HOANVE = 'HOANVE',
  SOATVE = 'SOATVE',
  QLHOANVE = 'QLHOANVE',
  QLHOADON = 'QLHOADON',
  QLPHIM = 'QLPHIM',
  QLLICHCHIEU = 'QLLICHCHIEU',
  QLPHONGCHIEU = 'QLPHONGCHIEU',
  QLDANHMUC = 'QLDANHMUC',
  QLCOMBO = 'QLCOMBO',
  QLKHUYENMAI = 'QLKHUYENMAI',
  QLNGUOIDUNG = 'QLNGUOIDUNG',
  BCTHONGKE = 'BCTHONGKE',
  KIOSK = 'KIOSK',
}

export default PermissionEnum;
